@startuml IoTPipeline
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title IoT Pipeline

map Application {
    Connection => Callback
}

map DPSv2_API {
}

map ADUv2_API {
}

map E4K_KV_API {
}

package Event_Pipeline
{
    map Optional_Policy1 {
    }

    package SubClients {
        map DPSv2 {
        }
        map ADUv2 {
        }
        map E4K_KV {
        }
    }

    map Connection {
    }

    map Optional_Policy2 {
    }

    map MQTT {
        az_mqtt => az_mqtt_impl
    }
}

Application --> DPSv2_API
Application --> ADUv2_API
Application --> E4K_KV_API

DPSv2_API --> Optional_Policy1
ADUv2_API --> Optional_Policy1
E4K_KV_API --> Optional_Policy1

Optional_Policy1 <--> DPSv2
Optional_Policy1 <--> ADUv2 
Optional_Policy1 <--> E4K_KV 

DPSv2 <--> Connection
ADUv2 <--> Connection
E4K_KV <--> Connection
Connection <--> Optional_Policy2 
Optional_Policy2 <--> MQTT
@enduml