@startuml

class az_hfsm_policy 
{
    +az_hfsm hfsm
    +az_hfsm_policy* inbound;
    +az_hfsm_policy* outbound;
    +az_hfsm_policy* pipeline;
    ---
    +az_hfsm_pipeline_send_inbound_event(event)
    +az_hfsm_pipeline_send_outbound_event(event)
}

class az_hfsm_pipeline
{
    -az_hfsm_policy* outbound_handler
    -az_hfsm_policy* inbound_handler
    -az_platform_mutex mutex
    ---
    +az_hfsm_pipeline_init(outbound_policy, inbound_policy)
    +az_hfsm_pipeline_post_inbound_event(event)
    +az_hfsm_pipeline_post_outbound_event(event)
    ---
    -az_hfsm_pipeline_sync_process_loop()   // Sync mode only
    ---
    +az_hfsm_pipeline_timer_create(az_hfsm_pipeline_timer* out_timer)
}

enum az_hfsm_event_type_pipeline
{
    // Sync mode only:
    AZ_HFSM_PIPELINE_EVENT_PROCESS_LOOP
}

az_hfsm_pipeline *-- az_hfsm_policy
az_hfsm_pipeline - az_hfsm_event_type_pipeline

@enduml
