@startuml Azure IoT HFSM

package "Run-To-Completion" as RTC {
    frame AzureIoTOrchestration {
        [Provisioning State Machine]
        [Hub State Machine]
        interface az_mqtt
        [MQTT State Machine Async Implementation]
    }
}

cloud AzureIoT {
    [Azure IoT Hub]
    [Azure IoT Device Provisioning]
}

package "Thread-Safe Queues" {
database DispatchingRequests
database DispatchingResponses
}

[Provisioning State Machine] <--> az_mqtt
[Hub State Machine] <--> az_mqtt
az_mqtt <--> [MQTT State Machine Async Implementation]
[MQTT State Machine Async Implementation] <--> AzureIoT
[Application] <--> [API]
[API] --> DispatchingRequests
DispatchingRequests --> AzureIoTOrchestration
AzureIoTOrchestration --> DispatchingResponses
DispatchingResponses --> API

@enduml
