@startuml

[API]
[Retry Policy] as Retry

package "IoT Provisioning Pipeline" {
    [Provisioning Policy] as DPS
    [MQTT Policy] as DPS_MQTT
    DPS -> DPS_MQTT
    DPS <- DPS_MQTT
}

package "IoT Hub Pipeline" {
    [Hub Policy] as Hub
    [MQTT Policy] as HUB_MQTT
    Hub -> HUB_MQTT
    Hub <- HUB_MQTT
}

API <-> Retry
Retry <--> DPS
Retry <--> Hub


@enduml
